name: Build & Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_VERSION: 24

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: |
          gh release delete ${{ github.ref_name }} --repo ${{ github.repository }} --yes || true
          gh release create ${{ github.ref_name }} --repo ${{ github.repository }} --title "${{ github.ref_name }}"
          
  release:
    needs: prepare
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        working-directory: ./sheet
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
      
      - run: npm install --legacy-peer-deps
      
      - name: Build React App
        run: npm run build

      - name: Compile
        run: npx electron-builder --publish never
      
      - name: Upload
        shell: bash
        run: |
          for file in release/*Setup*.exe release/*.dmg release/*.AppImage; do
            if [ -f "$file" ]; then
              gh release upload ${{ github.ref_name }} "$file" --repo ${{ github.repository }} --clobber
            fi
          done
